In [2]:
import torch
x=torch.empty(2,3,4)
print(x)

tensor([[[9.8091e-45, 0.0000e+00, 1.1210e-44, 0.0000e+00],
         [1.0000e+00, 1.0653e-38, 1.2952e-17, 9.3887e-43],
         [1.4013e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [9.8091e-45, 0.0000e+00, 1.1210e-44, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]])


In [3]:
print(torch.rand(2,3))

tensor([[0.1297, 0.9632, 0.2731],
        [0.3155, 0.4850, 0.4071]])


In [4]:
print(torch.zeros(3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [5]:
print(torch.ones(3,3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [6]:
x=torch.ones(3,3)
print(torch.ones(3,3).dtype)
print(torch.ones(3,3,dtype=torch.int).dtype)
print(torch.ones(3,3,dtype=int).dtype)
print(x.size())

torch.float32
torch.int32
torch.int64
torch.Size([3, 3])


In [7]:
x=torch.tensor([1.5,2.5,3.5])
print(x)

tensor([1.5000, 2.5000, 3.5000])


In [8]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x,y)
print(torch.add(x,y))
print(y.add_(x))
print(x*y)
print(torch.mul(x,y))
print(y.mul_(x))
print(x-y)

tensor([[0.2994, 0.9843],
        [0.5459, 0.9243]]) tensor([[0.1548, 0.6238],
        [0.4158, 0.3085]])
tensor([[0.4542, 1.6081],
        [0.9617, 1.2328]])
tensor([[0.4542, 1.6081],
        [0.9617, 1.2328]])
tensor([[0.1360, 1.5828],
        [0.5250, 1.1395]])
tensor([[0.1360, 1.5828],
        [0.5250, 1.1395]])
tensor([[0.1360, 1.5828],
        [0.5250, 1.1395]])
tensor([[ 0.1634, -0.5985],
        [ 0.0209, -0.2152]])


In [9]:
x=torch.rand(3,3)
print(x,x[1][1])
print(x[1,1])
print(x[:,1:])
print(x[:,:1])
print(x[0:2,1:3])
print(x[1,1].item()) #exact value

tensor([[0.4895, 0.3181, 0.9886],
        [0.9403, 0.9109, 0.4829],
        [0.8218, 0.3794, 0.9794]]) tensor(0.9109)
tensor(0.9109)
tensor([[0.3181, 0.9886],
        [0.9109, 0.4829],
        [0.3794, 0.9794]])
tensor([[0.4895],
        [0.9403],
        [0.8218]])
tensor([[0.3181, 0.9886],
        [0.9109, 0.4829]])
0.9109029173851013


In [10]:
x=torch.rand(4,4)
print(x)
y=x.view(16)
print(y)
y=x.view(-1,8)
print(y)
print(y.size())
x[1][1]=1
print(x)

tensor([[0.1524, 0.0472, 0.8638, 0.7111],
        [0.2106, 0.9653, 0.0542, 0.4019],
        [0.7411, 0.9333, 0.4684, 0.9289],
        [0.6719, 0.5349, 0.9960, 0.9427]])
tensor([0.1524, 0.0472, 0.8638, 0.7111, 0.2106, 0.9653, 0.0542, 0.4019, 0.7411,
        0.9333, 0.4684, 0.9289, 0.6719, 0.5349, 0.9960, 0.9427])
tensor([[0.1524, 0.0472, 0.8638, 0.7111, 0.2106, 0.9653, 0.0542, 0.4019],
        [0.7411, 0.9333, 0.4684, 0.9289, 0.6719, 0.5349, 0.9960, 0.9427]])
torch.Size([2, 8])
tensor([[0.1524, 0.0472, 0.8638, 0.7111],
        [0.2106, 1.0000, 0.0542, 0.4019],
        [0.7411, 0.9333, 0.4684, 0.9289],
        [0.6719, 0.5349, 0.9960, 0.9427]])


In [11]:
import numpy as np
a=torch.ones(2,2)
print(a)
print(type(a))
b=a.numpy() #to get a numpy array
print(b)
print(type(b))
a.add_(1)
print(a,b) #a,b share the same memory location so both changes

c=np.ones(2)
d=torch.from_numpy(c)
print(c,d)

tensor([[1., 1.],
        [1., 1.]])
<class 'torch.Tensor'>
[[1. 1.]
 [1. 1.]]
<class 'numpy.ndarray'>
tensor([[2., 2.],
        [2., 2.]]) [[2. 2.]
 [2. 2.]]
[1. 1.] tensor([1., 1.], dtype=torch.float64)


In [12]:
#Gradient Calculation using Autograd
import torch
x=torch.rand(3,requires_grad=True)
print(x)
y=x+2
print(y)
z=y*y*2
print(z)
z=z.mean()
print(z)

z.backward() #dz/dx
print(x.grad)

tensor([0.4386, 0.4606, 0.2109], requires_grad=True)
tensor([2.4386, 2.4606, 2.2109], grad_fn=<AddBackward0>)
tensor([11.8938, 12.1087,  9.7763], grad_fn=<MulBackward0>)
tensor(11.2596, grad_fn=<MeanBackward0>)
tensor([3.2515, 3.2807, 2.9479])


In [13]:
#x.requires_grad_(False)
#x.detach()
#with torch.no_grad():
import torch
x=torch.rand(3,requires_grad=True)
print(x)
x.requires_grad_(False)
print(x)
y=x.detach()
print(y)
with torch.no_grad():
    y=x+2
    print(x)

tensor([0.7657, 0.5900, 0.4537], requires_grad=True)
tensor([0.7657, 0.5900, 0.4537])
tensor([0.7657, 0.5900, 0.4537])
tensor([0.7657, 0.5900, 0.4537])


In [14]:
weights=torch.ones(3,requires_grad=True)
for _ in range(3):
    model_output=(weights*3).sum()
    model_output.backward()
    print(weights.grad)#Since in every iteration previous' iterations value is used so not incorrectgradient is obtained
    #weights.grad.zero_()  use this for correct gradient
for _ in range(3):
    model_output=(weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3.])
tensor([6., 6., 6.])
tensor([9., 9., 9.])
tensor([12., 12., 12.])
tensor([3., 3., 3.])
tensor([3., 3., 3.])


In [15]:
#Basic Backpropagation

x=torch.tensor(1.0)
w=torch.tensor(1.0,requires_grad=True)
y_hat=x*w
y=torch.tensor(2.0)

loss=(y_hat-y)**2
loss.backward()
print(w.grad)


x=torch.rand(3)
w=torch.rand(3,requires_grad=True)
y_hat=x*w
y=torch.rand(3)

loss=(y_hat-y)**2
v=torch.tensor([1,2,3])
loss.backward(v)
print(w.grad)

tensor(-2.)
tensor([ 0.1057,  0.3041, -0.0136])


In [16]:
#PREDICTION USING NUMPY 
import numpy as np

x=np.array([1,2,3,4],dtype=np.float32)
y=np.array([2,4,6,8],dtype=np.float32)

w=0.0
def forward(x):
    return w*x

def loss(y,y_predicted):
    return ((y_predicted-y)**2).mean()

#loss=1/N(wx-y)^2
#dloss/dw=2x/N(wx-y)
def gradient(x,y,y_predicted):
    return np.dot(2*x,(y_predicted-y)).mean()

print(forward(5))

learning_rate=0.01

for _ in range(10):
    y_pred=forward(x)
    l=loss(y,y_pred)
    grad=gradient(x,y,y_pred)
    w-= (learning_rate*grad)
    if _%1==0:
        print(w,l)
    
print(forward(5))

0.0
1.2 30.0
1.68 4.799999
1.8720000267028807 0.7680002
1.948800024986267 0.12288
1.9795200514793394 0.019660834
1.9918079876899717 0.0031456952
1.9967232251167295 0.00050332415
1.9986893200874327 8.053186e-05
1.9994757366180418 1.2884395e-05
1.9997902917861936 2.0613531e-06
9.998951458930968


In [17]:
#PREDICTION USING TORCH
import torch

x=torch.tensor([1,2,3,4],dtype=torch.float32)
y=torch.tensor([2,4,6,8],dtype=torch.float32)

w=torch.tensor(0.0,dtype=torch.float32,requires_grad=True)

def forward(x):
    return w*x

def loss(y,y_predicted):
    return ((y_predicted-y)**2).mean()

print(forward(5))

learning_rate=0.01

for _ in range(100):
    y_pred=forward(x)
    l=loss(y,y_pred)
    l.backward()
    with torch.no_grad():
        w-= (learning_rate*w.grad)
    
    w.grad.zero_()
    if _%1==0:
        print(w,l)
    
print(forward(5))

tensor(0., grad_fn=<MulBackward0>)
tensor(0.3000, requires_grad=True) tensor(30., grad_fn=<MeanBackward0>)
tensor(0.5550, requires_grad=True) tensor(21.6750, grad_fn=<MeanBackward0>)
tensor(0.7717, requires_grad=True) tensor(15.6602, grad_fn=<MeanBackward0>)
tensor(0.9560, requires_grad=True) tensor(11.3145, grad_fn=<MeanBackward0>)
tensor(1.1126, requires_grad=True) tensor(8.1747, grad_fn=<MeanBackward0>)
tensor(1.2457, requires_grad=True) tensor(5.9062, grad_fn=<MeanBackward0>)
tensor(1.3588, requires_grad=True) tensor(4.2673, grad_fn=<MeanBackward0>)
tensor(1.4550, requires_grad=True) tensor(3.0831, grad_fn=<MeanBackward0>)
tensor(1.5368, requires_grad=True) tensor(2.2275, grad_fn=<MeanBackward0>)
tensor(1.6063, requires_grad=True) tensor(1.6094, grad_fn=<MeanBackward0>)
tensor(1.6653, requires_grad=True) tensor(1.1628, grad_fn=<MeanBackward0>)
tensor(1.7155, requires_grad=True) tensor(0.8401, grad_fn=<MeanBackward0>)
tensor(1.7582, requires_grad=True) tensor(0.6070, grad_fn=<MeanBa

In [17]:
#PREDICTION USING TORCH including optimization

import torch
import torch.nn as nn #module for neural networks

x=torch.tensor([[1],[2],[3],[4]],dtype=torch.float32)
y=torch.tensor([[2],[4],[6],[8]],dtype=torch.float32)
x_test=torch.tensor([5],dtype=torch.float32)

n_samples,n_features=x.shape
print(n_samples,n_features)
input_size=n_features
output_size=n_features

model=nn.Linear(input_size,output_size)
print(model(x_test).item())

learning_rate=0.1
loss=nn.MSELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

for _ in range(1000):
    y_pred=model(x)
    l=loss(y,y_pred)
    l.backward()
    optimizer.step()
    optimizer.zero_grad()
    if _%100==0:
        [w,b]=model.parameters()
        print(w[0][0].item(),l)
    
print(model(x_test).item())

4 1
2.5401053428649902
2.5315637588500977 tensor(15.1816, grad_fn=<MseLossBackward0>)
1.984716773033142 tensor(0.0004, grad_fn=<MseLossBackward0>)
1.9992685317993164 tensor(8.2055e-07, grad_fn=<MseLossBackward0>)
1.999964952468872 tensor(1.8796e-09, grad_fn=<MseLossBackward0>)
1.9999983310699463 tensor(4.2064e-12, grad_fn=<MseLossBackward0>)
1.9999998807907104 tensor(1.4211e-14, grad_fn=<MseLossBackward0>)
2.0 tensor(0., grad_fn=<MseLossBackward0>)
2.0 tensor(0., grad_fn=<MseLossBackward0>)
2.0 tensor(0., grad_fn=<MseLossBackward0>)
2.0 tensor(0., grad_fn=<MseLossBackward0>)
10.0
